--- 
group: rails
address: 127.0.0.1
log_file: log/mongrel.log
port: "5000"
cwd: /srv/rails/quadomaniacy
environment: production
user: rails
pid_file: tmp/pids/mongrel.pid
servers: 6
config_script: config/mongrel_upload_progress.conf

